services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./.:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - django
    networks:
      - bot_network
    command: python bot.py
    
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./.:/usr/src/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - bot_network
    command: daphne -b 0.0.0.0 -p 8000 telegram_bot.asgi:application

volumes:
  postgres_data:

networks:
  bot_network:
