# Generated by Django 5.1.5 on 2025-02-01 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(null=True)),
                ('is_super_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('unique_members_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('max_member_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='PotentialAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'potential_admins',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('send_time', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scheduled_messages',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_user', to='admin_panel.group')),
            ],
            options={
                'db_table': 'user_groups',
                'unique_together': {('user_id', 'group')},
            },
        ),
    ]
