# Generated by Django 5.1.5 on 2025-02-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_member_count',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='group_name',
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='admin_panel.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to='scheduled_messages/'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='message_text',
            field=models.TextField(blank=True),
        ),
    ]
