# Generated by Django 5.1.6 on 2025-03-16 16:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_scheduledmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
